import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const handlers={},entries=new Map();let calls=0,offline=false;
const context={URL,self:{location:{origin:'https://mafia.test'},addEventListener:(type,fn)=>handlers[type]=fn},caches:{open:async()=>({match:async r=>entries.get(r.url),put:async(r,v)=>entries.set(r.url,v)})},fetch:async()=>{calls++;if(offline)throw Error('offline');return {ok:true,type:'basic',clone(){return this;}};}};
vm.runInNewContext(await readFile(new URL('../dist/sw.js',import.meta.url),'utf8'),context);
const background=[];
function request(path,options={}){let result;handlers.fetch({request:{url:new URL(path,'https://mafia.test').href,method:'GET',mode:'cors',...options},respondWith:p=>result=p,waitUntil:p=>background.push(p)});return result;}
await request('/assets/mafia-gold-icon.webp');await request('/assets/mafia-gold-icon.webp');assert.equal(calls,1);
await request('/game.js');await request('/game.js');assert.equal(calls,3);
offline=true;assert(await request('/game.js'));
assert.equal(request('/test-api'),undefined);assert.equal(request('https://external.test/file.js'),undefined);assert.equal(request('/game.js',{method:'POST'}),undefined);
console.log('PASS: cached images skip network; scripts refresh and work offline; API/external/POST requests bypass cache');
await Promise.all(background);
offline=false;
let releaseWrite;
const writeGate=new Promise(resolve=>releaseWrite=resolve);
context.caches.open=async()=>({match:async()=>undefined,put:()=>writeGate});
const fastResponse=await Promise.race([request('/slow-disk.js'),new Promise((_,reject)=>{const timer=setTimeout(()=>reject(Error('Response waited for cache write')),1000);timer.unref();})]);
assert(fastResponse.ok);
let finished=false;background.at(-1).then(()=>finished=true);
await Promise.resolve();assert.equal(finished,false);
releaseWrite();await background.at(-1);assert.equal(finished,true);
context.caches.open=async()=>{throw Error('Storage unavailable');};
assert((await request('/no-storage.js')).ok);
context.caches.open=async()=>({match:async()=>{throw Error('Cache read failed');},put:async()=>{throw Error('Quota exceeded');}});
assert((await request('/quota.js')).ok);
await Promise.all(background);
console.log('PASS: responses do not wait for cache writes; unavailable storage and quota errors preserve network access');
