-- Schema-only snapshot for isolated tests; no production data or credentials.
-- Captured 2026-09-12. Not a deployment migration.
create role anon; create role authenticated; create role service_role;
create table public.mafia_audit_events (id bigint generated by default as identity not null, room_code text, action text not null, status text not null, duration_ms integer default 0 not null, created_at timestamp with time zone default now() not null);
create table public.mafia_host_auth (id text default 'default'::text not null, pin_hash text not null, updated_at timestamp with time zone default now() not null);
create table public.mafia_host_preferences (id text default 'default'::text not null, settings jsonb default '{}'::jsonb not null, updated_at timestamp with time zone default now() not null);
create table public.mafia_host_sessions (token_hash text not null, created_at timestamp with time zone default now() not null, expires_at timestamp with time zone not null, last_seen timestamp with time zone default now() not null);
create table public.mafia_messages (id bigint generated by default as identity not null, room_code text not null, round integer default 1 not null, channel text not null, author_id text not null, author_name text not null, content text not null, created_at timestamp with time zone default now() not null);
create table public.mafia_players (room_code text not null, id text not null, name text not null, role text, alive boolean default true not null, action_target text, vote_target text, investigation_result text, joined_at timestamp with time zone default now() not null, session_token text, last_seen timestamp with time zone default now() not null, role_state jsonb default '{}'::jsonb not null, will_text text default ''::text not null, profile_token text, is_bot boolean default false not null, replacement_code text, replacement_expires_at timestamp with time zone);
create table public.mafia_profiles (profile_token text not null, nickname text not null, games integer default 0 not null, wins integer default 0 not null, village_wins integer default 0 not null, mafia_wins integer default 0 not null, independent_wins integer default 0 not null, correct_votes integer default 0 not null, created_at timestamp with time zone default now() not null, updated_at timestamp with time zone default now() not null, recovery_code text);
create table public.mafia_reports (id bigint generated by default as identity not null, room_code text not null, reporter_id text not null, target_id text, reason text not null, created_at timestamp with time zone default now() not null);
create table public.mafia_rooms (code text not null, host_token text not null, phase text default 'lobby'::text not null, round integer default 0 not null, mafia_count integer default 2 not null, last_eliminated text, last_saved boolean default false not null, winner text, created_at timestamp with time zone default now() not null, detective_count integer default 1 not null, detective_questions integer default 1 not null, jailed_player text, jailer_executions integer default 3 not null, doctor_last_target text, last_event text, last_deaths jsonb default '[]'::jsonb not null, enabled_roles jsonb default '{"doctor": true, "jailer": true, "lawyer": true, "detective": true}'::jsonb not null, linked_players jsonb default '[]'::jsonb not null, winner_player text, accused_player text, stats_recorded boolean default false not null, host_player_id text, host_session_hash text, phase_started_at timestamp with time zone default now() not null, phase_paused_at timestamp with time zone);
create table public.mafia_season_stats (profile_token text not null, season text not null, games integer default 0 not null, wins integer default 0 not null, updated_at timestamp with time zone default now() not null);
create table public.mafia_snapshots (id bigint generated by default as identity not null, room_code text not null, phase text not null, round integer not null, reason text not null, room_state jsonb not null, players_state jsonb not null, created_at timestamp with time zone default now() not null);
create table public.mafia_spectators (id text not null, room_code text not null, name text not null, session_token text not null, joined_at timestamp with time zone default now() not null, last_seen timestamp with time zone default now() not null);
alter table public.mafia_audit_events add constraint mafia_audit_events_pkey PRIMARY KEY (id);
alter table public.mafia_host_auth add constraint mafia_host_auth_pkey PRIMARY KEY (id);
alter table public.mafia_host_preferences add constraint mafia_host_preferences_pkey PRIMARY KEY (id);
alter table public.mafia_host_sessions add constraint mafia_host_sessions_pkey PRIMARY KEY (token_hash);
alter table public.mafia_messages add constraint mafia_messages_pkey PRIMARY KEY (id);
alter table public.mafia_players add constraint mafia_players_pkey PRIMARY KEY (room_code, id);
alter table public.mafia_profiles add constraint mafia_profiles_pkey PRIMARY KEY (profile_token);
alter table public.mafia_reports add constraint mafia_reports_pkey PRIMARY KEY (id);
alter table public.mafia_rooms add constraint mafia_rooms_pkey PRIMARY KEY (code);
alter table public.mafia_season_stats add constraint mafia_season_stats_pkey PRIMARY KEY (profile_token, season);
alter table public.mafia_snapshots add constraint mafia_snapshots_pkey PRIMARY KEY (id);
alter table public.mafia_spectators add constraint mafia_spectators_pkey PRIMARY KEY (room_code, id);
alter table public.mafia_profiles add constraint mafia_profiles_recovery_code_key UNIQUE (recovery_code);
alter table public.mafia_host_auth add constraint mafia_host_auth_id_check CHECK ((id = 'default'::text));
alter table public.mafia_host_preferences add constraint mafia_host_preferences_id_check CHECK ((id = 'default'::text));
alter table public.mafia_messages add constraint mafia_messages_content_check CHECK (((char_length(content) >= 1) AND (char_length(content) <= 240)));
alter table public.mafia_messages add constraint mafia_messages_channel_check CHECK ((channel = ANY (ARRAY['mafia'::text, 'jail'::text])));
alter table public.mafia_messages add constraint mafia_messages_room_code_fkey FOREIGN KEY (room_code) REFERENCES mafia_rooms(code) ON DELETE CASCADE;
alter table public.mafia_players add constraint mafia_players_role_check CHECK (((role IS NULL) OR (role = ANY (ARRAY['mafia'::text, 'mafia_boss'::text, 'doctor'::text, 'detective'::text, 'lawyer'::text, 'jailer'::text, 'vigilante'::text, 'witch'::text, 'serial_killer'::text, 'jester'::text, 'cupid'::text, 'escort'::text, 'citizen'::text, 'revealer'::text]))));
alter table public.mafia_players add constraint mafia_players_name_check CHECK (((char_length(name) >= 1) AND (char_length(name) <= 20)));
alter table public.mafia_players add constraint mafia_players_room_code_fkey FOREIGN KEY (room_code) REFERENCES mafia_rooms(code) ON DELETE CASCADE;
alter table public.mafia_profiles add constraint mafia_profiles_correct_votes_check CHECK ((correct_votes >= 0));
alter table public.mafia_profiles add constraint mafia_profiles_wins_check CHECK ((wins >= 0));
alter table public.mafia_profiles add constraint mafia_profiles_games_check CHECK ((games >= 0));
alter table public.mafia_profiles add constraint mafia_profiles_nickname_check CHECK (((char_length(nickname) >= 1) AND (char_length(nickname) <= 20)));
alter table public.mafia_profiles add constraint mafia_profiles_village_wins_check CHECK ((village_wins >= 0));
alter table public.mafia_profiles add constraint mafia_profiles_mafia_wins_check CHECK ((mafia_wins >= 0));
alter table public.mafia_profiles add constraint mafia_profiles_independent_wins_check CHECK ((independent_wins >= 0));
alter table public.mafia_reports add constraint mafia_reports_reason_check CHECK (((char_length(reason) >= 2) AND (char_length(reason) <= 160)));
alter table public.mafia_reports add constraint mafia_reports_room_code_fkey FOREIGN KEY (room_code) REFERENCES mafia_rooms(code) ON DELETE CASCADE;
alter table public.mafia_rooms add constraint mafia_rooms_jailer_executions_check CHECK (((jailer_executions >= 0) AND (jailer_executions <= 3)));
alter table public.mafia_rooms add constraint mafia_rooms_detective_count_check CHECK (((detective_count >= 0) AND (detective_count <= 8)));
alter table public.mafia_rooms add constraint mafia_rooms_detective_questions_check CHECK (((detective_questions >= 1) AND (detective_questions <= 5)));
alter table public.mafia_rooms add constraint mafia_rooms_phase_check CHECK ((phase = ANY (ARRAY['lobby'::text, 'reveal'::text, 'night'::text, 'day'::text, 'nomination'::text, 'trial'::text, 'verdict'::text, 'vote'::text, 'paused'::text, 'finished'::text])));
alter table public.mafia_season_stats add constraint mafia_season_stats_wins_check CHECK ((wins >= 0));
alter table public.mafia_season_stats add constraint mafia_season_stats_profile_token_fkey FOREIGN KEY (profile_token) REFERENCES mafia_profiles(profile_token) ON DELETE CASCADE;
alter table public.mafia_season_stats add constraint mafia_season_stats_games_check CHECK ((games >= 0));
alter table public.mafia_snapshots add constraint mafia_snapshots_room_code_fkey FOREIGN KEY (room_code) REFERENCES mafia_rooms(code) ON DELETE CASCADE;
alter table public.mafia_spectators add constraint mafia_spectators_room_code_fkey FOREIGN KEY (room_code) REFERENCES mafia_rooms(code) ON DELETE CASCADE;
CREATE OR REPLACE FUNCTION public.mafia_phase_clock()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if new.phase is distinct from old.phase then
    if new.phase = 'paused' then
      new.phase_paused_at := clock_timestamp();
    elsif old.phase = 'paused' and old.phase_paused_at is not null then
      new.phase_started_at := old.phase_started_at + (clock_timestamp() - old.phase_paused_at);
      new.phase_paused_at := null;
    else
      new.phase_started_at := clock_timestamp();
      new.phase_paused_at := null;
    end if;
  end if;
  return new;
end;
$function$;

CREATE TRIGGER mafia_phase_clock_update BEFORE UPDATE OF phase ON public.mafia_rooms FOR EACH ROW EXECUTE FUNCTION mafia_phase_clock();
