-- Lifecycle transitions must serialize on the room row. Service-only RPC;
-- authentication is repeated here after acquiring the lock, not just in Edge.
alter table public.mafia_rooms add column if not exists lifecycle_version bigint not null default 0;
alter table public.mafia_rooms add column if not exists match_id uuid not null default gen_random_uuid();
alter table public.mafia_players add column if not exists left_at timestamptz;
alter table public.mafia_rooms add column if not exists host_seen_at timestamptz not null default now();
create table if not exists public.mafia_leave_receipts (
 room_code text not null references public.mafia_rooms(code) on delete cascade,
 lifecycle_version bigint not null, credential_hash text not null,
 primary key(room_code,lifecycle_version,credential_hash)
);
alter table public.mafia_leave_receipts enable row level security;
revoke all on public.mafia_leave_receipts from public,anon,authenticated;
grant select,insert,delete on public.mafia_leave_receipts to service_role;

create or replace function public.mafia_return_to_lobby(
  p_code text, p_version bigint, p_host_token text,
  p_player_id text, p_player_token text
) returns jsonb
language plpgsql security invoker set search_path = '' as $$
declare
  r public.mafia_rooms%rowtype;
begin
  select * into r from public.mafia_rooms where code = p_code for update;
  if not found then return jsonb_build_object('error','ROOM_NOT_FOUND'); end if;
  if not coalesce((
    (p_host_token is not null and p_host_token <> '' and p_host_token = r.host_token)
    or exists (select 1 from public.mafia_players p where p.room_code = p_code
      and p.id = r.host_player_id and p.id = p_player_id
      and p.session_token is not null and p.session_token = p_player_token)
  ), false) then return jsonb_build_object('error','UNAUTHORIZED'); end if;
  if r.lifecycle_version <> p_version or p_version is null then
    return jsonb_build_object('error','STALE_GAME');
  end if;
  if r.phase <> 'finished' then return jsonb_build_object('error','INVALID_ACTION'); end if;

  -- Release deliberately vacated seats under the same transition lock.
  update public.mafia_rooms set phase='lobby' where code=p_code;
  delete from public.mafia_players where room_code=p_code and left_at is not null;
  -- Keep identities and preferences; erase all match-specific information.
  update public.mafia_players set role = null, role_state = '{}'::jsonb,
    alive = true, action_target = null, vote_target = null,
    investigation_result = null, will_text = '', replacement_code = null,
    replacement_expires_at = null where room_code = p_code;
  delete from public.mafia_messages where room_code = p_code;
  delete from public.mafia_reports where room_code = p_code;
  delete from public.mafia_snapshots where room_code = p_code;
  update public.mafia_rooms set phase = 'lobby', round = 0,
    lifecycle_version = lifecycle_version + 1,
    phase_started_at = now(), phase_paused_at = null,
    enabled_roles = enabled_roles - array['discussion_state','pending_shot','leader_election',
      'vote_summary','admin_access','paused_phase'],
    jailed_player = null, accused_player = null, jailer_executions = 3,
    doctor_last_target = null, linked_players = '[]'::jsonb,
    last_event = 'returned_to_lobby', last_deaths = '[]'::jsonb,
    last_eliminated = null, last_saved = false, winner = null,
    winner_player = null, stats_recorded = false where code = p_code;
  return jsonb_build_object('ok',true);
end;
$$;
revoke all on function public.mafia_return_to_lobby(text,bigint,text,text,text) from public, anon, authenticated;
grant execute on function public.mafia_return_to_lobby(text,bigint,text,text,text) to service_role;

-- Assignments are generated by the trusted Edge handler, but the seat set,
-- authority and generation must still be verified under the transaction lock.
create or replace function public.mafia_start_match(
 p_code text, p_version bigint, p_host_token text, p_player_id text,
 p_player_token text, p_assignments jsonb, p_settings jsonb,
 p_mafia integer, p_detectives integer, p_questions integer
) returns jsonb language plpgsql security invoker set search_path = '' as $$
declare r public.mafia_rooms%rowtype; seats text[]; assigned text[]; n integer;
begin
 select * into r from public.mafia_rooms where code=p_code for update;
 if not found then return jsonb_build_object('error','ROOM_NOT_FOUND'); end if;
 if not coalesce(((p_host_token is not null and p_host_token<>'' and p_host_token=r.host_token)
  or exists(select 1 from public.mafia_players p where p.room_code=p_code
   and p.id=r.host_player_id and p.id=p_player_id and p.session_token is not null
   and p.session_token=p_player_token)),false) then return jsonb_build_object('error','UNAUTHORIZED'); end if;
 if p_version is null or r.lifecycle_version<>p_version then return jsonb_build_object('error','STALE_GAME'); end if;
 if r.phase not in ('lobby','finished') then return jsonb_build_object('error','INVALID_ACTION'); end if;
 select array_agg(id order by id),count(*) into seats,n from public.mafia_players where room_code=p_code and left_at is null;
 if n<2 or n>20 then return jsonb_build_object('error','INVALID_PLAYER_COUNT'); end if;
 if jsonb_typeof(p_assignments) is distinct from 'array' then return jsonb_build_object('error','INVALID_ASSIGNMENTS'); end if;
 select array_agg(x->>'id' order by x->>'id') into assigned from jsonb_array_elements(p_assignments) x;
 if assigned is distinct from seats then return jsonb_build_object('error','ROSTER_CHANGED'); end if;
 if p_mafia is null or p_mafia<1 or p_mafia>greatest(1,(n-1)/2)
  or p_detectives is null or p_detectives<0 or p_detectives>n-p_mafia
  or p_questions is null or p_questions not between 1 and 5
  or jsonb_typeof(p_settings) is distinct from 'object' then return jsonb_build_object('error','INVALID_SETTINGS'); end if;
 if exists(select 1 from jsonb_array_elements(p_assignments) x where
  x->>'role' is null or x->>'role' not in ('mafia','mafia_boss','citizen','doctor','detective','lawyer','jailer',
  'vigilante','witch','serial_killer','jester','cupid','escort','revealer')
  or jsonb_typeof(x->'state') is distinct from 'object') then return jsonb_build_object('error','INVALID_ASSIGNMENTS'); end if;
 if (select count(*) from jsonb_array_elements(p_assignments) x where x->>'role' in ('mafia','mafia_boss'))<>p_mafia
  or (select count(*) from jsonb_array_elements(p_assignments) x where x->>'role'='detective')<>p_detectives
  then return jsonb_build_object('error','INVALID_ASSIGNMENTS'); end if;
 update public.mafia_rooms set phase='lobby' where code=p_code;
 delete from public.mafia_players where room_code=p_code and left_at is not null;
 update public.mafia_players p set role=x->>'role',role_state=x->'state',alive=true,
  action_target=null,vote_target=null,investigation_result=null,will_text='',
  replacement_code=null,replacement_expires_at=null
  from jsonb_array_elements(p_assignments) x where p.room_code=p_code and p.id=x->>'id';
 delete from public.mafia_messages where room_code=p_code;
 delete from public.mafia_reports where room_code=p_code;
 delete from public.mafia_snapshots where room_code=p_code;
 update public.mafia_rooms set phase='reveal',round=1,lifecycle_version=lifecycle_version+1,match_id=gen_random_uuid(),
  phase_started_at=now(),phase_paused_at=null,mafia_count=p_mafia,detective_count=p_detectives,
  detective_questions=p_questions,enabled_roles=(p_settings-array['discussion_state','pending_shot','vote_summary','paused_phase']) - case when r.phase='finished' then array['admin_access'] else array[]::text[] end,
  jailed_player=null,accused_player=null,jailer_executions=3,doctor_last_target=null,
  linked_players='[]'::jsonb,last_event='game_started',last_deaths='[]'::jsonb,
  last_eliminated=null,last_saved=false,winner=null,winner_player=null,stats_recorded=false where code=p_code;
 return jsonb_build_object('ok',true);
end;
$$;
revoke all on function public.mafia_start_match(text,bigint,text,text,text,jsonb,jsonb,integer,integer,integer) from public,anon,authenticated;
grant execute on function public.mafia_start_match(text,bigint,text,text,text,jsonb,jsonb,integer,integer,integer) to service_role;

-- All existing insert/delete paths (join, bots and lobby kicks) participate in
-- the same room lock as start, including clients that raced the Edge precheck.
create or replace function public.mafia_guard_membership()
returns trigger language plpgsql security invoker set search_path='' as $$
declare r public.mafia_rooms%rowtype; room_id text;
begin
 room_id := case when tg_op='DELETE' then old.room_code else new.room_code end;
 select * into r from public.mafia_rooms where code=room_id for update;
 if not found then
  if tg_op='DELETE' then return old; end if;
  raise exception 'ROOM_NOT_FOUND';
 end if;
 if r.phase<>'lobby' then raise exception 'GAME_STARTED'; end if;
 if tg_op='DELETE' then return old; end if;
 if (select count(*) from public.mafia_players where room_code=room_id)>=20 then raise exception 'ROOM_FULL'; end if;
 if exists(select 1 from public.mafia_players where room_code=room_id and lower(btrim(name))=lower(btrim(new.name))) then raise exception 'NAME_TAKEN'; end if;
 return new;
end;
$$;
revoke all on function public.mafia_guard_membership() from public,anon,authenticated;
drop trigger if exists mafia_membership_guard on public.mafia_players;
create trigger mafia_membership_guard before insert or delete on public.mafia_players
for each row execute function public.mafia_guard_membership();

create or replace function public.mafia_leave_room(
 p_code text,p_version bigint,p_host_token text,p_player_id text,p_player_token text
) returns jsonb language plpgsql security invoker set search_path='' as $$
declare r public.mafia_rooms%rowtype; departing public.mafia_players%rowtype;
 owner_leaving boolean; successor text; d jsonb; ids jsonb; idx integer; removed integer; v_credential_hash text;
 cursor_value integer; at_ms bigint; active_phase text;
begin
 select * into r from public.mafia_rooms where code=p_code for update;
 if not found then return jsonb_build_object('error','ROOM_NOT_FOUND'); end if;
 v_credential_hash:=encode(sha256(convert_to(jsonb_build_array(p_host_token,p_player_id,p_player_token)::text,'UTF8')),'hex');
 if exists(select 1 from public.mafia_leave_receipts receipt where receipt.room_code=p_code
  and receipt.lifecycle_version=p_version and receipt.credential_hash=v_credential_hash)
  then return jsonb_build_object('ok',true,'hostPlayerId',r.host_player_id,'lifecycleVersion',r.lifecycle_version,'replayed',true); end if;
 owner_leaving := coalesce(p_host_token<>'' and p_host_token=r.host_token,false);
 select * into departing from public.mafia_players where room_code=p_code and id=p_player_id
  and session_token is not null and session_token=p_player_token and left_at is null;
 if not owner_leaving and departing.id is null then return jsonb_build_object('error','UNAUTHORIZED'); end if;
 if p_version is null or p_version<>r.lifecycle_version then return jsonb_build_object('error','STALE_GAME'); end if;
 at_ms := floor(extract(epoch from clock_timestamp())*1000);
 if departing.id is not null then
  update public.mafia_players set left_at=now(),alive=false,session_token=null,
   vote_target=null,action_target=null,replacement_code=null,replacement_expires_at=null,
   role_state=role_state||jsonb_build_object('ack',true,'elimination',jsonb_build_object('reason','player_left','round',r.round,'at',at_ms))
   where room_code=p_code and id=departing.id;
  update public.mafia_players set vote_target=null where room_code=p_code and vote_target=departing.id;
  -- An already submitted detective question remains spent, but must not expose
  -- the departed target's role. Other roles can choose a new valid target.
  update public.mafia_players set action_target=case when role='detective'
    then array_to_string(array_replace(string_to_array(action_target,','),departing.id,'SKIP'),',')
    else null end where room_code=p_code
   and departing.id=any(regexp_split_to_array(action_target,'[,:]'));
  r.jailed_player := case when r.jailed_player=departing.id then null else r.jailed_player end;
  r.doctor_last_target := case when r.doctor_last_target=departing.id then null else r.doctor_last_target end;
  if r.linked_players ? departing.id then r.linked_players:='[]'::jsonb; end if;
  d:=r.enabled_roles->'discussion_state';
  if d is not null and d->'order' ? departing.id then
   select (ordinality-1)::integer into removed from jsonb_array_elements_text(d->'order') with ordinality where value=departing.id;
   idx:=coalesce((d->>'cursor')::integer,0);
   if d->>'mode'='turns' then idx:=idx+greatest(0,floor((coalesce(nullif((d->>'pausedAt')::bigint,0),at_ms)-(d->>'turnStartedAt')::bigint)/((d->>'seconds')::numeric*1000))::integer); end if;
   select coalesce(jsonb_agg(value order by ordinality),'[]') into ids from jsonb_array_elements_text(d->'order') with ordinality where value<>departing.id;
   cursor_value:=greatest(0,idx-case when removed<idx then 1 else 0 end);
   d:=d||jsonb_build_object('order',ids,'cursor',cursor_value,'version',coalesce((d->>'version')::integer,0)+1,
    'turnStartedAt',case when removed=idx then coalesce(nullif((d->>'pausedAt')::bigint,0),at_ms) else (d->>'turnStartedAt')::bigint+(idx-coalesce((d->>'cursor')::integer,0))*(d->>'seconds')::integer*1000 end,
    'finished',coalesce((d->>'finished')::boolean,false) or (d->>'mode'='turns' and cursor_value>=jsonb_array_length(ids)), 'roulette',null);
   r.enabled_roles:=jsonb_set(r.enabled_roles,'{discussion_state}',d);
  end if;
  active_phase:=case when r.phase='paused' then r.enabled_roles->>'paused_phase' else r.phase end;
  if r.accused_player=departing.id and active_phase in ('trial','verdict') then
   r.accused_player:=null;r.round:=r.round+1;r.phase:='night';r.phase_paused_at:=null;r.phase_started_at:=now();
   r.enabled_roles:=r.enabled_roles-'paused_phase';
   update public.mafia_players set action_target=null,vote_target=null where room_code=p_code;
  end if;
  if r.enabled_roles->'pending_shot'->>'playerId'=departing.id
    or r.enabled_roles->'pending_shot'->>'target'=departing.id then
   -- Once a shot is committed it cannot be redirected if its target leaves.
   update public.mafia_players set role_state=role_state||'{"bullets":0}'::jsonb
    where room_code=p_code and id=r.enabled_roles->'pending_shot'->>'playerId';
   r.phase:=r.enabled_roles->'pending_shot'->>'nextPhase';r.round:=(r.enabled_roles->'pending_shot'->>'nextRound')::integer;
   r.enabled_roles:=r.enabled_roles-'pending_shot';r.phase_started_at:=now();r.phase_paused_at:=null;
  end if;
 end if;
 if owner_leaving or r.host_player_id=departing.id then
  select id into successor from public.mafia_players where room_code=p_code and left_at is null
   and not is_bot and last_seen>now()-interval '30 seconds' order by alive desc,joined_at,id limit 1;
  r.host_player_id:=successor;
  r.host_token:=gen_random_uuid()::text; -- Previous controller cannot regain authority using an old token.
  r.enabled_roles:=(r.enabled_roles-'admin_access')||jsonb_build_object('controller_spectator',coalesce((select not alive from public.mafia_players where room_code=p_code and id=successor),false));
 end if;
 if not exists(select 1 from public.mafia_players where room_code=p_code and left_at is null and not is_bot) then
  r.phase:='finished';r.winner:='cancelled';r.winner_player:=null;
 end if;
 if r.phase not in ('lobby','finished') then
  r.enabled_roles:=r.enabled_roles||'{"departure_pending":true}'::jsonb;
 end if;
 update public.mafia_rooms set phase=r.phase,round=r.round,host_token=r.host_token,host_player_id=r.host_player_id,
  enabled_roles=r.enabled_roles,jailed_player=r.jailed_player,doctor_last_target=r.doctor_last_target,
  linked_players=r.linked_players,accused_player=r.accused_player,phase_started_at=r.phase_started_at,
  phase_paused_at=r.phase_paused_at,winner=r.winner,winner_player=r.winner_player,last_event='player_left' where code=p_code;
 if r.phase='lobby' and departing.id is not null then delete from public.mafia_players where room_code=p_code and id=departing.id; end if;
 update public.mafia_rooms set lifecycle_version=lifecycle_version+1 where code=p_code returning lifecycle_version into r.lifecycle_version;
 insert into public.mafia_leave_receipts values(p_code,p_version,v_credential_hash);
 return jsonb_build_object('ok',true,'hostPlayerId',r.host_player_id,'lifecycleVersion',r.lifecycle_version,'replayed',false);
end;
$$;
revoke all on function public.mafia_leave_room(text,bigint,text,text,text) from public,anon,authenticated;
grant execute on function public.mafia_leave_room(text,bigint,text,text,text) to service_role;

create or replace function public.mafia_presence(p_code text,p_host_token text,p_player_id text,p_player_token text)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare r public.mafia_rooms%rowtype; caller_id text; controller_seen timestamptz; successor text;
 owner_present boolean;
begin
 select * into r from public.mafia_rooms where code=p_code for update;
 if not found then return jsonb_build_object('error','ROOM_NOT_FOUND'); end if;
 owner_present:=coalesce(p_host_token<>'' and p_host_token=r.host_token,false);
 select id into caller_id from public.mafia_players where room_code=p_code and id=p_player_id
  and session_token is not null and session_token=p_player_token and left_at is null;
 if not owner_present and caller_id is null then return jsonb_build_object('error','UNAUTHORIZED'); end if;
 if caller_id is not null then update public.mafia_players set last_seen=clock_timestamp() where room_code=p_code and id=caller_id; end if;
 if owner_present then
  update public.mafia_rooms set host_seen_at=clock_timestamp() where code=p_code;
  return jsonb_build_object('ok',true);
 end if;
 if r.host_player_id is not null then
  select last_seen into controller_seen from public.mafia_players where room_code=p_code and id=r.host_player_id and left_at is null and (alive or coalesce((r.enabled_roles->>'controller_spectator')::boolean,false));
 else controller_seen:=r.host_seen_at; end if;
 -- A short network loss never removes a seat, redeals a role, or rotates control.
 if controller_seen is null or controller_seen<clock_timestamp()-interval '45 seconds' then
  select id into successor from public.mafia_players where room_code=p_code and left_at is null
   and not is_bot and last_seen>clock_timestamp()-interval '30 seconds' order by alive desc,joined_at,id limit 1;
  if successor is not null then
   update public.mafia_rooms set host_player_id=successor,host_token=gen_random_uuid()::text,lifecycle_version=lifecycle_version+1,
    host_seen_at=clock_timestamp(),enabled_roles=(enabled_roles-'admin_access')||jsonb_build_object('controller_spectator',coalesce((select not alive from public.mafia_players where room_code=p_code and id=successor),false)) where code=p_code;
  end if;
 end if;
 return jsonb_build_object('ok',true);
end;
$$;
revoke all on function public.mafia_presence(text,text,text,text) from public,anon,authenticated;
grant execute on function public.mafia_presence(text,text,text,text) to service_role;

-- Each PostgREST request runs a transaction. Lock the parent room and compare
-- the Edge request generation for every write, including delayed later writes
-- of a multi-query handler. RPC transitions use the same room lock.
create or replace function public.mafia_fence_write()
returns trigger language plpgsql security invoker set search_path='' as $$
declare headers jsonb; room_id text; expected text; actual bigint; row_data jsonb;
begin
 headers:=coalesce(nullif(current_setting('request.headers',true),'')::jsonb,'{}'::jsonb);
 expected:=headers->>'x-mafia-generation';
 if expected is null then
  if tg_op='DELETE' then return old; else return new; end if;
 end if;
 row_data:=case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end;
 room_id:=case when tg_table_name='mafia_rooms' then row_data->>'code' else row_data->>'room_code' end;
 if room_id is null then
  if tg_op='DELETE' then return old; else return new; end if;
 end if;
 if room_id is distinct from headers->>'x-mafia-room' or expected !~ '^[0-9]+$' then raise exception 'STALE_GAME'; end if;
 select lifecycle_version into actual from public.mafia_rooms where code=room_id for update;
 if found and actual::text<>expected then raise exception 'STALE_GAME'; end if;
 if tg_op='DELETE' then return old; else return new; end if;
end;
$$;
revoke all on function public.mafia_fence_write() from public,anon,authenticated;
create trigger mafia_generation_fence before update or delete on public.mafia_rooms for each row execute function public.mafia_fence_write();
create trigger mafia_generation_fence before insert or update or delete on public.mafia_players for each row execute function public.mafia_fence_write();
create trigger mafia_generation_fence before insert or update or delete on public.mafia_messages for each row execute function public.mafia_fence_write();
create trigger mafia_generation_fence before insert or update or delete on public.mafia_reports for each row execute function public.mafia_fence_write();
create trigger mafia_generation_fence before insert or update or delete on public.mafia_snapshots for each row execute function public.mafia_fence_write();

-- A row trigger runs after UPDATE has already locked its player row. Taking
-- the room lock there alone reverses the RPC lock order (room, then players)
-- and can deadlock. Acquire the room before the statement locks any rows.
create or replace function public.mafia_lock_request_room()
returns trigger language plpgsql security invoker set search_path='' as $$
declare headers jsonb; room_id text; expected text; actual bigint;
begin
 headers:=coalesce(nullif(current_setting('request.headers',true),'')::jsonb,'{}'::jsonb);
 expected:=headers->>'x-mafia-generation';room_id:=headers->>'x-mafia-room';
 if expected is null then return null; end if;
 if room_id is null or room_id !~ '^[0-9]{4}$' or expected !~ '^[0-9]+$' then raise exception 'STALE_GAME'; end if;
 select lifecycle_version into actual from public.mafia_rooms where code=room_id for update;
 if found and actual::text<>expected then raise exception 'STALE_GAME'; end if;
 return null;
end;
$$;
revoke all on function public.mafia_lock_request_room() from public,anon,authenticated;
create trigger mafia_lock_room_first before insert or update or delete on public.mafia_rooms for each statement execute function public.mafia_lock_request_room();
create trigger mafia_lock_room_first before insert or update or delete on public.mafia_players for each statement execute function public.mafia_lock_request_room();
create trigger mafia_lock_room_first before insert or update or delete on public.mafia_messages for each statement execute function public.mafia_lock_request_room();
create trigger mafia_lock_room_first before insert or update or delete on public.mafia_reports for each statement execute function public.mafia_lock_request_room();
create trigger mafia_lock_room_first before insert or update or delete on public.mafia_snapshots for each statement execute function public.mafia_lock_request_room();

create or replace function public.mafia_kick_player(p_code text,p_version bigint,p_host_token text,p_player_id text,p_player_token text,p_target text)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare r public.mafia_rooms%rowtype; successor text;
begin
 select * into r from public.mafia_rooms where code=p_code for update;
 if not found then return jsonb_build_object('error','ROOM_NOT_FOUND');end if;
 if not coalesce(p_host_token<>'' and p_host_token=r.host_token,false) and not exists
  (select 1 from public.mafia_players where room_code=p_code and id=r.host_player_id and id=p_player_id and session_token=p_player_token and left_at is null and alive)
  then return jsonb_build_object('error','UNAUTHORIZED');end if;
 if p_version is null or p_version<>r.lifecycle_version then return jsonb_build_object('error','STALE_GAME');end if;
 if r.phase<>'lobby' then return jsonb_build_object('error','GAME_STARTED');end if;
 delete from public.mafia_players where room_code=p_code and id=p_target;
 if not found then return jsonb_build_object('error','PLAYER_NOT_FOUND');end if;
 if r.host_player_id=p_target then
  select id into successor from public.mafia_players where room_code=p_code and not is_bot and alive and left_at is null and last_seen>now()-interval '30 seconds' order by joined_at,id limit 1;
  update public.mafia_rooms set host_player_id=successor,enabled_roles=enabled_roles-'controller_spectator' where code=p_code;
 end if;
 update public.mafia_rooms set lifecycle_version=lifecycle_version+1 where code=p_code;
 return jsonb_build_object('ok',true);
end;
$$;
revoke all on function public.mafia_kick_player(text,bigint,text,text,text,text) from public,anon,authenticated;
grant execute on function public.mafia_kick_player(text,bigint,text,text,text,text) to service_role;
