alter table public.mafia_rooms add column if not exists host_player_id text;
alter table public.mafia_players add column if not exists replacement_code text;
alter table public.mafia_players add column if not exists replacement_expires_at timestamptz;
alter table public.mafia_profiles add column if not exists recovery_code text unique;

create table if not exists public.mafia_spectators (
  id text not null,
  room_code text not null references public.mafia_rooms(code) on delete cascade,
  name text not null,
  session_token text not null,
  joined_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  primary key (room_code, id)
);
alter table public.mafia_spectators enable row level security;

create table if not exists public.mafia_snapshots (
  id bigint generated by default as identity primary key,
  room_code text not null references public.mafia_rooms(code) on delete cascade,
  phase text not null,
  round integer not null,
  reason text not null,
  room_state jsonb not null,
  players_state jsonb not null,
  created_at timestamptz not null default now()
);
alter table public.mafia_snapshots enable row level security;
create index if not exists mafia_snapshots_room_created_idx on public.mafia_snapshots(room_code, created_at desc);

create table if not exists public.mafia_audit_events (
  id bigint generated by default as identity primary key,
  room_code text,
  action text not null,
  status text not null,
  duration_ms integer not null default 0,
  created_at timestamptz not null default now()
);
alter table public.mafia_audit_events enable row level security;
create index if not exists mafia_audit_events_room_created_idx on public.mafia_audit_events(room_code, created_at desc);
