const API = 'https://unsxzbrpqvppecjnirqx.supabase.co/functions/v1/mafia-room?forceFunctionRegion=ap-southeast-1';
const $ = (selector) => document.querySelector(selector);
let game = null;
let hostToken = '';
let hostAccessToken = localStorage.getItem('mafia-host-access-token') || '';
let playerToken = '';
let playerId = '';
let mafiaCount = 3;
let detectiveCount = 1;
let detectiveQuestions = 3;
const detectiveQuestionCount = (value) => Number.isFinite(Number(value)) && value != null ? Math.max(1, Math.min(5, Math.round(Number(value)))) : 3;
let enabledRoles = { doctor: true, detective: true, lawyer: true, jailer: true, vigilante: false, witch: false, serial_killer: false, jester: false, cupid: false, escort: false, godfather_innocent: true, mafia_kill_start_round: 2, mafia_kill_mode: 'always', mafia_kill_enabled: true, reveal_dead_roles: false, allow_no_vote: true, full_trial: true, kids_mode: false };
let spectatorToken = '';
Object.assign(enabledRoles, { discussion_mode: 'turns', discussion_seconds: 180, speaker_seconds: 30 });
let spectatorId = '';
let spectatorMode = false;
let delegatedHostMode = false;
let profileToken = localStorage.getItem('mafia-profile-token') || crypto.randomUUID();
localStorage.setItem('mafia-profile-token', profileToken);
let pollTimer;
let pollingEpoch = 0;
let busyCount = 0;
let apiWarmed = false;
let setupStep = 1;
let lobbyPane = 'setup';
let lobbyPlayerPage = 0;
let phaseStartedAt = Date.now();
let phaseDuration = Number(localStorage.getItem('mafia-phase-seconds')) || 60;
let soundEnabled = localStorage.getItem('mafia-sound') !== 'off';
let localHistory = [];
let preferenceSaveTimer;

